### ISSUE TITLE
Indentation for game version value is too short (Cosmetic)

### ISSUE THREAD

**Issue by SilmorSenedlen** [suurjaak/h3sed#11]
Good day
I noticed that the names of any versions except "Shadow of Dead" do not fit into the field reserved for game version.

![h3sed_v2 4_game_version_visual_glitch](https://github.com/suurjaak/h3sed/assets/6761903/6087746d-4409-487d-a7af-27e337bb560b)
h3sed  v2.4

**Comment by suurjaak** [comment]
Thank you for drawing my attention to this, will soon issue another release where this is fixed. 

While you're at it, any other cosmetic issues to bring up? Or other suggestions about the program?

**Comment by SilmorSenedlen** [comment]
Thx for your work! ; )

> While you're at it, any other cosmetic issues to bring up? Or other suggestions about the program?

I can't say that I use editor often or a lot, so maybe I could have overlooked something, but so far I haven't noticed anything else.

> Or other suggestions about the program?

From what I personally lack for convenience:
1) On the main attributes tab, display the original value of the hero's stats and additionally, the value added by artifacts.
Something like this:
![h3sed_suggestions_01](https://github.com/suurjaak/h3sed/assets/6761903/fbedcc0a-d184-450e-b09e-b48b70739ff1)

And if possible:
3) Add a switch so that the hero's level is recalculated based on the amount of experience.
4) Similar to the previous, but on contrary, amount of experience recalculated based on the level of hero.

**Comment by suurjaak** [comment]
Good ideas, thank you, I will add these.

**Comment by suurjaak** [comment]
Fixed the layout bug in the newly released v2.5, and implemented your other suggestions as well. 

Thank you.

**Comment by SilmorSenedlen** [comment]
> Fixed the layout bug in the newly released v2.5, and implemented your other suggestions as well.

Great work!
