### ISSUE TITLE
Pikemen don't appear in Army display

### ISSUE THREAD

**Issue by WolffHobbitStomper** [suurjaak/h3sed#12]
Pikemen (unit ID 0) don't display army when loading save into h3sed.
The problem is in Army.py line 223

#if not unit or not count or not name: values.append({})
->       if not count or not name: values.append({})

Removing the check for "not unit' resolves it for me.
[111_Adelaide.zip](https://github.com/user-attachments/files/15861229/111_Adelaide.zip)

**Comment by suurjaak** [comment]
Nice catch, thank you. 

Will make a fixed release soon.

**Comment by suurjaak** [comment]
Fixed in the newly released v2.5.

Thank you for reporting this, and pinpointing the problem as well.
