### ISSUE TITLE
1.7

### ISSUE THREAD

**Issue by qazomardok** [suurjaak/h3sed#2]
Please, update for 1.7.0: there are new heroes, creatures, mobs and other

**Comment by suurjaak** [comment]
Can you be more specific - which version of Heroes3 has new creatures?

**Comment by qazomardok** [comment]
The new city Factory in HM&M3: Hota.
Heroes: https://www.heroes3towns.com/?town=factory&ver=2&page=heroes
Units: https://www.heroes3towns.com/?town=factory&ver=2&page=units

**Comment by suurjaak** [comment]
New heroes should not matter in the context of h3sed. 

However, support for new creatures can be added. I will look into adding Factory creature support to the program.

**Comment by suurjaak** [comment]
Released v1.8, with support for HotA Factory creatures; also the Sleepkeeper artifact. 

Let me know if there is something else amiss.
