### ISSUE TITLE
not all heroes show up (Galthran)

### ISSUE THREAD

**Issue by seriousgranpa** [suurjaak/h3sed#3]
i tried to strip him of any artifacts - still missing from the list
version of save editor is 1.8
hota 1.7 version

[google drive](https://drive.google.com/file/d/1Gy77YTLt42Cfhd9Cmhd_f_bX4kkx9UI7/view?usp=sharing)

ps thanks for the program, it is amazing!!(not sarcasm, its just Galthran is an total asshole, who 3rd time in a row picks wrong skills and refusing to show up in a list to force fix is ignorance )

**Comment by suurjaak** [comment]
I was actually just about to release a new version. 

However, that one also does not seem to detect this hero, so I will postpone the release. 

All in all, it detects 39 heroes in the savefile you linked, which is a little low. In fact, from the heroes of the Red player, it only finds Clavius and Nimbus. 

I will try to track this problem down.

**Comment by suurjaak** [comment]
Found the problem - was not accounting for hero names in other code pages like Cyrillic. 

Will release a fixed version soon. 

Out of curiosity - how does the editor display the hero names in your setup - all good, you see them as proper Cyrillic?

**Comment by suurjaak** [comment]
The gaps in the index are just from plentiful columns like artifacts or spells, currently out of scroll window in your screenshot. Those can be toggled off and on from the buttons below. 

Released version 2.0 now, with a number of fixes and improvements. Now it finds 198 heroes in your savefile. That looks just about right. 

Let me know how it fares.

**Comment by seriousgranpa** [comment]
> The gaps in the index are just from plentiful columns like artifacts or spells, currently out of scroll window in your screenshot. Those can be toggled off and on from the buttons below.
> 
> Released version 2.0 now, with a number of fixes and improvements. Now it finds 198 heroes in your savefile. That looks just about right.
> 
> Let me know how it fares.

okay, that makes sense, considering the amount of skipped heroes
thanks for your work, i will try out later

**Comment by seriousgranpa** [comment]
okay, i tried and everything works perfectly
thanks for your efforts!
