### ISSUE TITLE
vcmi save support

### ISSUE THREAD

**Issue by kutovy** [suurjaak/h3sed#4]
Hi! Thanks for the great tool.

Unfortunately, it's not currently compatible with [VCMI](https://vcmi.eu/) version (*.vsgm1).

Making it compatible with VCMI would be a great addition, as VCMI has become an increasingly popular way to play H3 these days, especially on Android.

**Comment by suurjaak** [comment]
I wouldn't mind adding support for other savegame formats. 

So I looked a bit into VCMI. Sadly, it looks like the VCMI savegame is not a file format as such, but more like a raw memory dump from the program. I have not found even a general description, much less a specification, and trying to figure it all out from VCMI source code is not an easy task.
