### ISSUE TITLE
support for Armageddon's Blade

### ISSUE THREAD

**Issue by awtur** [suurjaak/h3sed#5]
Hi. Any plans to extend support to Armageddon's Blade and other HOMM3 entries? Noticed it won't recognize save files from AB. Not sure why they're different.

**Comment by suurjaak** [comment]
Can you share a savegame from AB?

**Comment by awtur** [comment]
Sure, attached. The message I'm getting is "not a valid save file".
[125.zip](https://github.com/suurjaak/h3sed/files/15392670/125.zip)

**Comment by suurjaak** [comment]
Thank you. Looks like adding support for the older versions is very doable, at least for Armageddon's Blade. Will also look into supporting the original Restoration of Erathia.

**Comment by suurjaak** [comment]
Does this export look about right for the savefile you provided?
[Heroes from 125.zip](https://github.com/suurjaak/h3sed/files/15407191/Heroes.from.125.zip)

**Comment by awtur** [comment]
> Does this export look about right for the savefile you provided? [Heroes from 125.zip](https://github.com/suurjaak/h3sed/files/15407191/Heroes.from.125.zip)

Yes, that's correct. Thanks so much.

**Comment by suurjaak** [comment]
Released v2.1, with support for savefiles from Armageddon's Blade, and also the original Restoration of Erathia. 

Let me know if there are any problems.
