### ISSUE TITLE
Can't open files on MacOS

### ISSUE THREAD

**Issue by alexkharlamov** [suurjaak/h3sed#6]
Running the latest on MacOS Ventura, GUI opens, but the game directory doesn't show any files. When you try to open a file manually using system dialog it says "Not a valid save game file". Tried with regular H3 ROE and HOTA files.

**Comment by suurjaak** [comment]
Can you send one such savefile?

**Comment by alexkharlamov** [comment]
[test.GM1.zip](https://github.com/suurjaak/h3sed/files/15448831/test.GM1.zip)

Sure - see this one, for example - tested with a bunch of different save files from different versions of H3, can't get any of them to open

**Comment by suurjaak** [comment]
This savefile itself looks fine. 

Can you go to the log window after attempting to open a file (program menu Help -> Show log window) and paste the log contents here?

**Comment by alexkharlamov** [comment]
11:38:30.592	Error opening /Users/alex/Downloads/test.GM1.

		Traceback (most recent call last):
		  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/h3sed/gui.py", line 392, in load_savefile
		    savefile = metadata.Savefile(filename)
		               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
		  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/h3sed/metadata.py", line 991, in __init__
		    self.read()
		  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/h3sed/metadata.py", line 1003, in read
		    with gzip.GzipFile(self.filename, "rb") as f: self.raw = bytearray(f.read())
		                                                                       ^^^^^^^^
		  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/gzip.py", line 301, in read
		    return self._buffer.read(size)
		           ^^^^^^^^^^^^^^^^^^^^^^^
		  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/_compression.py", line 118, in readall
		    while data := self.read(sys.maxsize):
		                  ^^^^^^^^^^^^^^^^^^^^^^
		  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/gzip.py", line 490, in read
		    self._read_eof()
		  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/h3sed/main.py", line 88, in read_eof_py3
		    self._read_exact(8)
		    ^^^^^^^^^^^^^^^^
		AttributeError: '_GzipReader' object has no attribute '_read_exact'

11:38:30.596	/Users/alex/Downloads/test.GM1 is not a valid gzipped file.

**Comment by suurjaak** [comment]
Aha, thank you, that explains it. A problem with newer Python versions. 

I will look into making a new release that fixes the issue.

**Comment by suurjaak** [comment]
By the way, how did you install the program? I can send you a fixed preview version to try out, before making a public release.

**Comment by alexkharlamov** [comment]
I installed via pip, but I can also check out a branch from Github, I'm also an engineer :)

**Comment by suurjaak** [comment]
Excellent, you can just run `pip install h3sed_2.2.dev0-src.zip` on this:
[h3sed_2.2.dev0-src.zip](https://github.com/suurjaak/h3sed/files/15459066/h3sed_2.2.dev0-src.zip)

**Comment by alexkharlamov** [comment]
It's working, I can open files now, thank you!!

**Comment by suurjaak** [comment]
Excellent, I will make an official release soon. 

Is everything else in the program working fine? Changing heroes, saving changes, exporting to HTML - all good? Since I don't have a Mac computer and macOS is actively hostile to virtual machines, I haven't been able to test the program in macOS myself.

**Comment by suurjaak** [comment]
The new v2.2 release fixes the file opening issue.
