### ISSUE TITLE
Trojan Trojan:Win32/Wacatac.B!ml found in Windows executable

### ISSUE THREAD

**Issue by arnehaese** [suurjaak/h3sed#7]
Hi, 

the executalbles (standalone and the one in setup downloadable on https://suurjaak.github.io/h3sed/downloads.html) are infected with Trojan:Win32/Wacatac.B!ml - you might want to recompile :) 

Thx, best,
A

**Comment by arnehaese** [comment]
Thx for the quick answer - I see, had sth similar some years ago with Autoit automation on Windows, did not guess this could be similar here - sorry for any confusion I might have caused. 

Thx a lot, best,
A

**Comment by suurjaak** [comment]
Thank you! 

Where did this infection notice come from? If it came from Microsoft Defender or the like, I can try contacting them to run a proper analysis and whitelist the application, because a built-in antivirus flagging the program makes it quite impossible for people to use..

**Comment by arnehaese** [comment]
Indeed Microsoft Defender on upto date patched Win 11 - thx a lot :)

**Comment by suurjaak** [comment]
Thank you, I've submitted a false-positive report to Microsoft. 

Will keep this issue open for now.

**Comment by suurjaak** [comment]
So far, so good, screenshot from the Microsoft Security website:

![image](https://github.com/suurjaak/h3sed/assets/719382/7d0c2b32-6e77-48d8-9aa6-38b535accf29)

Guess we need to wait for a human to look it over.

**Comment by suurjaak** [comment]
I will also try using a custom-built PyInstaller for new releases, hopefully resulting in less false-positive reports from antivirals.
