### ISSUE TITLE
Won't edit RoE saves from GOG version of game

### ISSUE THREAD

**Issue by WolffHobbitStomper** [suurjaak/h3sed#8]
Won't edit RoE saves from the GOG Heroes 3 Complete version of game.

After a bit of experimenting I found the problem. 
The (campaign) save file ID's are
RoE  2A 00
AB    2A 01
SoD 2A 02
In roe.py you need to update version ID's

VersionByteRanges = {
    "version_major":  (16, 42),
    "version_minor":  ( 0,  0),
}

**Comment by suurjaak** [comment]
Can you attach one such RoE savefile here?

**Comment by WolffHobbitStomper** [comment]
Save attached. 
I've successfully edited saves for RoE with the suggested change by running from the modified source. Tested with base game and with the HD resolution mod.


[RoE.CGM.gz](https://github.com/user-attachments/files/15778985/RoE.CGM.gz)

**Comment by suurjaak** [comment]
Thank you. Will issue a new release soon.

**Comment by suurjaak** [comment]
The new v2.3 release should resolve this issue. 

Thank you for the fix.
