### ISSUE TITLE
Equiping Statesman's Medal causes crash

### ISSUE THREAD

**Issue by WolffHobbitStomper** [suurjaak/h3sed#9]
Equipping the Statesman's Medal to the neck slot in game causes a runtime error when the editor loads the hero with it equipped.

Problem found metadata.py has this marked for side slot not neck slot.

Corrected file and test save attached.

[test.zip](https://github.com/user-attachments/files/15797555/test.zip)

**Comment by WolffHobbitStomper** [comment]
I decieded to check other artifacts and found the Pendant of Negativity is missing.
I've updated metadata.py with it added.
While doing this I also found that there appears to be an offset error in the Inventory slots. 
Any item placed into Inventory slot #1 doesn't appear in game, and there appears to be a slot in game appearing after slot #64
See the attached save.
NB. To view this behavour in game you need to open hero and then go directly to the backpack without clicking anything else or the game sorts the backpack. 

[test2.zip](https://github.com/user-attachments/files/15798446/test2.zip)

**Comment by suurjaak** [comment]
Thank you. The Pendant of Negativity is actually present but being wrongly named as Pendant of Agitation. 

Looking further, I found some more problems with artifacts. Will issue another release soon.

**Comment by suurjaak** [comment]
Would you happen to have Armageddon's Blade available as well? If yes, can you check if the inventory slots issue occurs there the same way as in Erathia?

**Comment by WolffHobbitStomper** [comment]
I decieded to check other artifacts and found the Pendant of Negativity is missing.
I've updated metadata.py with it added.
While doing this I also found that there appears to be an offset error in the Inventory slots. 
Any item placed into Inventory slot #1 doesn't appear in game, and there appears to be a slot in game appearing after slot #64
See the attached save.
NB. To view this behavour in game you need to open hero and then go directly to the backpack without clicking anything else or the game sorts the backpack. 

[test2.zip](https://github.com/user-attachments/files/15798446/test2.zip)

**Comment by WolffHobbitStomper** [comment]
Did some testing both AB and RoE show the inventory slot offset issue. See attached files.
From my investigation the Complete edition of the games seems to use to the SOD save format for all campaigns.
ie. Space for 5th side slot is allocated/reserved before inventory contents for all campaigns. Maybe the original RoE game version 16 save file is different from the version 42 format?

[test3.zip](https://github.com/user-attachments/files/15811887/test3.zip)

**Comment by suurjaak** [comment]
Indeed it looks like your version of the game actually uses the SOD format. With some caveats, e.g. the savefile reserves space for side slot 5 but does not use it. 

When I try with an actual original Restoration of Erathia game version, the current logic in h3sed works as intended. 

Looks like I will have to introduce different behavior depending on the specific `version_major` value.

However, with Armageddon's Blade there is a problem, since it only has one value for `version_major`. Not yet sure how to solve that..

**Comment by suurjaak** [comment]
Released version 2.4 with a number of fixes. 

For Restoration of Erathia, it uses `version_major` to determine whether to assume older or newer format. 

And solved the ambiguity in Armageddon's Blade by adding a menu option for it.
